apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: image-scan
spec:
  pipelineSpec:
    tasks:
    - name: image-scan
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:mikelear/leartech-pipeline-catalog/tasks/security-scan/image-scan.yaml@main
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - name: ""
          resources: {}
  podTemplate:
    tolerations:
    - key: sku
      operator: Equal
      value: build
      effect: NoSchedule
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
